import type { WellnessResource } from '@/types';

export const curatedWellnessResources: WellnessResource[] = [
  {
    id: 'CWR001',
    title: 'Beginner\'s Guide to Meditation',
    description: 'Learn the basics of meditation and start your journey to inner peace.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Mindfulness',
    type: 'article',
    contentUrl: '#',
    duration: '10 min read',
    'data-ai-hint': 'meditation peace',
  },
  {
    id: 'CWR002',
    title: '10 Quick & Healthy Breakfast Ideas',
    description: 'Fuel your day with these easy and nutritious breakfast recipes.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Nutrition',
    type: 'article',
    contentUrl: '#',
    duration: '15 min read',
    'data-ai-hint': 'healthy food',
  },
  {
    id: 'CWR003',
    title: 'Morning Yoga Flow for Energy',
    description: 'A 15-minute yoga routine to energize your body and mind.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Fitness',
    type: 'video',
    contentUrl: '#',
    duration: '15 min video',
    'data-ai-hint': 'yoga park',
  },
  {
    id: 'CWR004',
    title: 'The Importance of Sleep for Wellbeing',
    description: 'Discover how quality sleep impacts your overall health and tips for better sleep.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Lifestyle',
    type: 'article',
    contentUrl: '#',
    duration: '12 min read',
    'data-ai-hint': 'sleep wellness',
  },
  {
    id: 'CWR005',
    title: 'Guided Deep Breathing Exercise',
    description: 'A short audio guide to practice deep breathing for stress relief.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Mindfulness',
    type: 'audio',
    contentUrl: '#',
    duration: '5 min audio',
    'data-ai-hint': 'breathing calm',
  },
  {
    id: 'CWR006',
    title: 'Understanding Hydration',
    description: 'Learn why water is crucial for your body and how to stay properly hydrated.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Nutrition',
    type: 'article',
    contentUrl: '#',
    duration: '8 min read',
    'data-ai-hint': 'water health',
  },
];

export const audioBookSummaries: WellnessResource[] = [
  {
    id: 'ABS001',
    title: 'Atomic Habits by James Clear',
    description: 'An easy and proven way to build good habits and break bad ones. Key insights on making small changes for remarkable results.',
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'book habit',
    category: 'Self-Improvement',
    type: 'audio',
    contentUrl: '#',
    duration: '20 min audio',
  },
  {
    id: 'ABS002',
    title: 'Thinking, Fast and Slow by Daniel Kahneman',
    description: 'Explore the two systems that drive the way we think. Learn about cognitive biases and how to make better decisions.',
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'brain thought',
    category: 'Psychology',
    type: 'audio',
    contentUrl: '#',
    duration: '25 min audio',
  },
  {
    id: 'ABS003',
    title: 'Sapiens by Yuval Noah Harari',
    description: 'A brief history of humankind, from the Stone Age to the present day, exploring how Homo sapiens came to dominate the world.',
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'history humanity',
    category: 'History',
    type: 'audio',
    contentUrl: '#',
    duration: '30 min audio',
  },
   {
    id: 'ABS004',
    title: 'The Power of Now by Eckhart Tolle',
    description: 'A guide to spiritual enlightenment, focusing on living in the present moment to achieve peace and happiness.',
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'spiritual mindfulness',
    category: 'Spirituality',
    type: 'audio',
    contentUrl: '#',
    duration: '22 min audio',
  },
];
